# 코드 15.3 air.toml 설정 내용

root = "."
tmp_dir = "tmp"

[build]
# 이전 형식의 shell 명령. 'make'를 사용해도 된다.
cmd = "go build -o ./tmp/main ."
# 'cmd'에서 바이너리 파일을 생성한다.
bin = "tmp/main"

# 80번 포트를 사용하도록 실행 시 인수를 지정
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include.ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["asserts", "tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true